### ISSUE TITLE
validate tfa url failed: http handler request exception

### ISSUE THREAD

**Issue by ntkathole** [RedHatQE/tfacon#1]
**Describe the bug**

```
./go/bin/tfacon validate
LaunchID: 	 739
LaunchName:
ProjectName: 	 demo
AuthToken: 	 XXXXXX-XXXXX-XXXXX
RPURL: 	 https://reportportal-smqe
Client: 	 &{<nil> <nil> <nil> 0s}
TFAURL: 	 https://tfa

Validating....
validate tfa url failed: http handler request exception, status code is:404, err is %!w(<nil>)
```

There is an error during validation:
validate error: validate tfa url failed: http handler request exception, status code is:404, err is %!w(<nil>)

**To Reproduce**
1. go get -u github.com/RedHatQE/tfacon
2. Configure tfa yaml
3. Run` tfacon validate`

**Expected behavior**
Successfully validated.

**Desktop (please complete the following information):**
 - OS: macOS Monterey | 12.0.1
 - go version go1.16.4 darwin/amd64

**Additional context**

**Comment by ntkathole** [comment]
@JunqiZhang0 ^

**Comment by JunqiZhang0** [comment]
@ntkathole looking at it, will get back to you by the end of the week

**Comment by JunqiZhang0** [comment]
Hi @ntkathole` I debugged it and reproduced it. I think it's either, you are not on VPN, or tfa-c is down. Let me know if you still have questions. tfa-c is up now, you can test it

**Comment by ntkathole** [comment]
I see it is working fine now. Thanks.
