### ISSUE TITLE
Provide hint/comment on prediction 

### ISSUE THREAD

**Issue by ntkathole** [RedHatQE/tfacon#13]
**Is your feature request related to a problem? Please describe.**

As a TFAcon user, I just get prediction on failures. But still I have to look into all failed tests logs to see if prediction is correct. It will be very useful if I get some comment or hint (parsed from logs using some regex) that will explain why particular failure predicted as system issue or product issue or automation issue. 

As an example, lets look into following failed test, where prediction given by TFA classifier i.e. Predicted system issue, is correct. But still as a QE, I have to look into logs and verify it's correct prediction. 

![Screenshot 2022-04-21 at 12 54 15 PM](https://user-images.githubusercontent.com/16951913/164401043-16d32116-b94e-4fcb-b17b-59832ffc20c5.png)

![Screenshot 2022-04-21 at 12 55 23 PM](https://user-images.githubusercontent.com/16951913/164400921-31f6ae4e-da64-4553-8e37-c2970431a234.png)

**Describe the solution you'd like**

I would like TFA classifier to provide hint/comment on failure and TFAcon to update that comment with prediction as shown below.

![Screenshot 2022-04-21 at 12 56 23 PM](https://user-images.githubusercontent.com/16951913/164401786-c56282c2-0280-40a8-94bf-b0795eabd014.png)

**Comment by JunqiZhang0** [comment]
Hi @ntkathole , Recommendation Engine is now integrated with tfacon, you can do tfacon run -r to get result for Recommendation Engine. tfacon will update the recommendations in the comment field of you test item. RE will tell you the 3 most similar test times to the current test item. Would it solve your problem?

**Comment by ntkathole** [comment]
Thanks @JunqiZhang0 I am able to see some comments from recommendation engine. I will enable and observe how its helpful. I am closing this issue since RE serves main purpose. If required, I will open new issues for RE enhancements.
