### ISSUE TITLE
tfacon times out randomly even after waiting for about 180 seconds

### ISSUE THREAD

**Issue by kasturinarra** [RedHatQE/tfacon#26]
**Describe the bug**
When trying to run tfacon with load where there are about 800+cases and 63 items to be investigated i see that tfacon fails with error even after waiting for about 180 minutes. 

**To Reproduce**
1. Go to ocp reportportal
2. Delete all launches from the project prow
3. Rebuild jenkins job

**Expected behavior**
we could see that tfacon times out randomly even after waiting for about 180 seconds and results are not being classified.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
As suggested we have set the conurrency to true, increased the timeout in our script from 60 seconds to 180 seconds , import and classification is running serially and not parallely. I will provide all the links to reportportal, jenkins jobs, scripts we are using in a separate email.

**Comment by JunqiZhang0** [comment]
looking at it

**Comment by kasturinarra** [comment]
@JunqiZhang0 i think we can close this issue as we currently do not see it from our end and everything works fine., thanks !!
