### ISSUE TITLE
Test item attributes are being overwritten by the AI Prediction attribute

### ISSUE THREAD

**Issue by clacroix12** [RedHatQE/tfacon#3]
**Describe the bug**
tfacon is overwriting existing test item attributes. 

**To Reproduce**
1. Upload a report to ReportPortal where failed test items have attributes.
2. View a test item and notice its existing attributes.
3. Run tfacon against that launch ID.
4. Open the launch in ReportPortal and navigate to that same test item. It should now have an "AI Prediction" attribute.
5. Notice that the previously existing attributes are gone.

**Expected behavior**
The test case should have the new "AI Prediction" attribute alongside its previous attributes.

**Screenshots**
Example of the test case (with no failure since this is from a different launch, but the attributes should be the same)
![Screen Shot 2021-12-16 at 11 02 20 AM](https://user-images.githubusercontent.com/1605721/146432644-538679d9-8b02-4627-ae2e-32d3bd68476c.png)

Example post-tfacon:
![Screen Shot 2021-12-16 at 11 00 39 AM](https://user-images.githubusercontent.com/1605721/146432676-04c51655-1b13-47b2-941f-f545ec4f0ff4.png)

**Comment by petr-balogh** [comment]
Hello @JunqiZhang0 , please do you have any update on this issue?
Thanks

**Comment by JunqiZhang0** [comment]
Hi @petr-balogh @clacroix12  the fix will be merged today, but the new release will be triggered next week（contains all big fixes filed recently）

**Comment by petr-balogh** [comment]
<img width="670" alt="Screen Shot 2022-01-13 at 9 46 18 AM" src="https://user-images.githubusercontent.com/16169617/149296396-1c31fb0d-0d20-4d74-a739-a64fc44f09ca.png">
I can confirm it's fixed now. Thanks!
