### ISSUE TITLE
existing comment added to the beginning of cases if we add comments by batch

### ISSUE THREAD

**Issue by juzhao** [RedHatQE/tfacon#54]
**Describe the bug**
checked In one Prow job, TFA predicts system issue for the cases, there is already one comment  "No Similar Test Case Found", see the picture
![before](https://user-images.githubusercontent.com/22743651/227130461-fb7360b7-d338-4441-8e82-28faee5e2dbc.png)

analyze cases, they are failed for chrome issue, edit all the cases by batch, add comment
```
caused by: Chrome failed to start: crashed.
(unknown error: DevToolsActivePort file doesn't exist)
```
save the change, will find the existing comment "No Similar Test Case Found" is added to the beginning
![after](https://user-images.githubusercontent.com/22743651/227131650-34d17aa6-c02e-479f-9352-762fd89cbf5c.png)

if we edit only one case, will only see the comment added by ourselves, no existing comment added to the beginning

**Expected behavior**
only see comments added by user

**Screenshots**

**Additional context**

**Comment by JunqiZhang0** [comment]
Hi @juzhao , this is the expected behaviour, we made it this way so it won't overwrite the original comment

**Comment by juzhao** [comment]
@JunqiZhang0 thanks, then we could close this issue
